name: Linting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run:  pip install -r docs/requirements.txt

    - name: Install linters
      run:  pip install -U rstcheck[sphinx] sphinx-lint

    - name: Run sphinx-lint
      run:  sphinx-lint docs/

    - name: Run rstcheck
      run:  rstcheck --recursive docs/
